name = "my-worker"
main = "src/index.ts"
compatibility_date = "2023-10-04"
workers_dev = true

[env.production]
workers_dev = false
routes = [
	{ pattern = "location.mplibunao.tech", custom_domain = true }
]
